Update id_test

diff --git a/id_test b/id_test
--- a/id_test
+++ b/id_test
@@ -3,9 +3,9 @@
 printf "Test #4: UID test\n"
 printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
 
-write_pass=false
-container_write_pass=false
-uid_pass=false
+write_pass=
+container_write_pass=
+uid_pass=
 
 my_id=$(id -u $USER)
 
@@ -14,110 +14,135 @@ my_id=$(id -u $USER)
 printf "Without the --userns=keep-id option\n"
 printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
 echo "UID: $my_id"
-echo "UID in container:" $(podman run -v /home/opc:/home/opc ubuntu:16.04 bash -c "id -u \$USER")
+if podman run --root /tmp/podman_tmp -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "id -u \$USER"; then
 
-printf "Create a file from within the container... "
-if podman run --quiet -v /home/opc:/home/opc ubuntu:16.04 bash -c "touch /home/$USER/my_uid" ; then
-	printf "done\n"
+        echo "UID in container:" $(podman run  --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "id -u \$USER")
+
 else
-	printf "failed\n"
-	echo "TEST FAILED"
-	exit 1
+        printf "failed\n"
+        echo "TEST FAILED"
+        exit 1
 fi
 
-file_owner=$(stat -c '%u' /home/$USER/my_uid)
+printf "Create a file from within the container... "
+if podman run --storage-opt overlay.ignore_chown_errors=true --quiet --runroot=/tmp/podman_tmp --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "touch /tests/my_uid" ; then
+        printf "done\n"
+else
+        printf "failed\n"
+        echo "TEST FAILED"
+        exit 1
+fi
+
+file_owner=$(stat -c '%u' /scratch/ismailiy/test-podman/my_uid)
 
 printf "Check if file owner uid is the same as current uid... "
 if [ "$my_id" -eq "$file_owner" ] ; then
-	uid_pass=true
-	printf "done\n"
+        uid_pass=true
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 
 printf "Check if file is writable from outside of the container... "
-if touch /home/$USER/my_uid ; then
-	write_pass=true
-	printf "done\n"
+if touch /scratch/ismailiy/test-podman/my_uid ; then
+        write_pass=true
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 
-rm /home/$USER/my_uid
+rm /scratch/ismailiy/test-podman/my_uid
 
 printf "Create a file from outside the container... "
-if touch /home/$USER/my_uid ; then
-	printf "done\n"
+if touch /scratch/ismailiy/test-podman/my_uid ; then
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 
 printf "Check if file is writable from within the container... "
-if podman run -v /home/opc:/home/opc ubuntu:16.04 bash -c "touch /home/$USER/my_uid" ; then
-	container_write_pass=true
-	printf "done\n"
+if podman run --runroot=/tmp/podman_tmp --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "touch /tests/my_uid" ; then
+        container_write_pass=true
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
+podman run --runroot=/tmp/podman_tmp --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "touch /tests/my_uid"i#echo "$write_pass"  "$uid_pass"  "$container_write_pass"
 if [ "$write_pass" -a "$uid_pass" -a "$container_write_pass" ] ; then
 #if [ "$uid_pass" -a "$container_write_pass" ] ; then
-	echo "TEST PASSED"
+        echo "TEST PASSED"
+else
+        echo "TEST FAILED"
 fi
 
 # repeating test with option --userns=keep-id
+
+write_pass=
+container_write_pass=
+uid_pass=
 
 echo
 printf "With the --userns=keep-id option\n"
 printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
 echo "UID: $my_id"
-echo "UID in container:" $(podman run --userns=keep-id -v /home/opc:/home/opc ubuntu:16.04 bash -c "id -u \$USER")
+if podman run --userns=keep-id  --root /tmp/podman_tmp -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "id -u \$USER"; then
 
-printf "Create a file from within the container... "
-if podman run --userns=keep-id -v /home/opc:/home/opc ubuntu:16.04 bash -c "touch /home/$USER/my_uid" ; then
-	printf "done\n"
+        echo "UID in container:" $(podman run  --userns=keep-id  --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "id -u \$USER")
+
 else
-	printf "failed\n"
-	echo "TEST FAILED"
-	exit 1
+        printf "failed\n"
+        echo "TEST FAILED"
+        exit 1
 fi
 
-file_owner=$(stat -c '%u' /home/$USER/my_uid)
+printf "Create a file from within the container... "
+if podman run --runroot=/tmp/podman_tmp --root=/tmp/podman_tmp  --userns=keep-id -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "touch /tests/my_uid" ; then
+        printf "done\n"
+else
+        printf "failed\n"
+        echo "TEST FAILED"
+        exit 1
+fi
+
+file_owner=$(stat -c '%u' /scratch/ismailiy/test-podman/my_uid)
 
 printf "Check if file owner uid is the same as current uid... "
 if [ "$my_id" -eq "$file_owner" ] ; then
-	uid_pass=true
-	printf "done\n"
+        uid_pass=true
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 
 printf "Check if file is writable from outside of the container... "
-if touch /home/$USER/my_uid ; then
-	write_pass=true
-	printf "done\n"
+if touch /scratch/ismailiy/test-podman/my_uid ; then
+        write_pass=true
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 
-rm /home/$USER/my_uid
+rm /scratch/ismailiy/test-podman/my_uid
 
 printf "Create a file from outside the container... "
-if touch /home/$USER/my_uid ; then
-	printf "done\n"
+if touch /scratch/ismailiy/test-podman/my_uid ; then
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 
 printf "Check if file is writable from within the container... "
-if podman run --userns=keep-id -v /home/opc:/home/opc ubuntu:16.04 bash -c "touch /home/$USER/my_uid" ; then
-	container_write_pass=true
-	printf "done\n"
+if podman run --runroot=/tmp/podman_tmp --root=/tmp/podman_tmp  --userns=keep-id -v /scratch/ismailiy/test-podman:/tests ubuntu:16.04 bash -c "touch /tests/my_uid" ; then
+        container_write_pass=true
+        printf "done\n"
 else
-	printf "failed\n"
+        printf "failed\n"
 fi
 printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
 if [ "$write_pass" -a "$uid_pass" -a "$container_write_pass" ] ; then
 #if [ "$uid_pass" -a "$container_write_pass" ] ; then
-	echo "TEST PASSED"
+        echo "TEST PASSED"
+else
+        echo "TEST FAILED"
 fi
