Update save_load_test

diff --git a/save_load_test b/save_load_test
--- a/save_load_test
+++ b/save_load_test
@@ -3,31 +3,31 @@ printf "Save/load test\n"
 printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
 
 printf "Building image.. "
-if podman build ./base_dockerfile -t "load_test" >/dev/null 2>&1 ; then
-	printf "done\n"
+if podman build --root=/tmp/podman_tmp --runroot=/tmp/podman_tmp ./base_dockerfile -t "load_test" ; then
+        printf "done\n"
 else
-	printf "failed\n"
-	echo "TEST FAILED"
-	exit 1
+        printf "failed\n"
+        echo "TEST FAILED"
+        exit 1
 fi
 printf "Saving to testing.rar.. "
-if podman save load_test -o testing.tar >/dev/null 2>&1 ; then
-	printf "done\n"
+if podman save load_test  --root=/tmp/podman_tmp -o testing.tar ; then
+        printf "done\n"
 else
-	printf "failed\n"
-	echo "TEST FAILED"
-	exit 1
+        printf "failed\n"
+        echo "TEST FAILED"
+        exit 1
 fi
 
-podman image rm load_test --force >/dev/null 2>&1
+podman image rm load_test  --root=/tmp/podman_tmp --force >/dev/null 2>&1
 
-podman load -i testing.tar --quiet
+podman load --root=/tmp/podman_tmp -i testing.tar --quiet
 
-uid_pass=false
-write_pass=false
+uid_pass=
+write_pass=
 
 printf "Create a file from within the container... "
-if podman run  -v /home/opc:/home/opc load_test bash -c "touch /home/$USER/my_uid" ; then
+if podman run  --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests load_test bash -c "touch /tests/my_uid" ; then
         printf "done\n"
 else
         printf "failed\n"
@@ -36,7 +36,7 @@ else
 fi
 
 my_id=$(id -u $USER)
-file_owner=$(stat -c '%u' /home/$USER/my_uid)
+file_owner=$(stat -c '%u' /scratch/ismailiy/test-podman/my_uid)
 printf "Check if file owner uid is the same as current uid... "
 if [ "$my_id" -eq "$file_owner" ] ; then
         uid_pass=true
@@ -46,7 +46,7 @@ else
 fi
 
 printf "Check if file is writable from outside of the container... "
-if touch /home/$USER/my_uid ; then
+if touch /scratch/ismailiy/test-podman/my_uid ; then
         write_pass=true
         printf "done\n"
 else
@@ -54,10 +54,10 @@ else
 fi
 
 if [ $uid_pass -a $write_pass ] ; then
-	echo TEST PASSED
+        echo TEST PASSED
 else
-	echo TEST FAILED
+        echo TEST FAILED
 fi
 
-rm /home/$USER/my_uid
+rm /scratch/ismailiy/test-podman/my_uid
 rm "testing.tar"
