Added some prints and refactored

diff --git a/hpl/hpl_test b/hpl/hpl_test
--- a/hpl/hpl_test
+++ b/hpl/hpl_test
@@ -1,11 +1,23 @@
 #!/bin/bash
+printf "HPL test\n"
+printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
 
 #export PMIX_MCA_gds=hash
-
-podman build . -t hpl-test
+printf "Attempting to build base container.. "
+if podman build . -t hpl-test > /dev/null 2>&1 ; then
+	printf "done\n"
+else
+	printf " failed\n"
+	exit 1
+fi
 
 #mpirun -np 2 --mca btl openib,tcp,self --mca orte_tmpdir_base /tmp/podman-mpirun podman run -v $HOME:$HOME --env-host --net=host --pid=host --ipc=host -w $PWD hpl-test:latest
 
-podman run --userns=keep-id -v $HOME:$HOME --env-host --net=host --pid=host --ipc=host -w $PWD hpl-test:latest mpirun -np 2 --mca btl openib,tcp,self /hpl/bin/ubuntu/xhpl
+printf "Attempting to run HPL\n"
+if podman run --userns=keep-id -v $HOME:$HOME --env-host --net=host --pid=host --ipc=host -w $PWD hpl-test:latest mpirun -np 2 --mca btl openib,tcp,self /hpl/bin/ubuntu/xhpl ; then
+	printf "TEST PASSED\n"
+else
+	printf "TEST FAILED\n"
+fi
 
 #export PMIX_MCA_gds=
diff --git a/ring/ring_test b/ring/ring_test
--- a/ring/ring_test
+++ b/ring/ring_test
@@ -1,16 +1,39 @@
 #!/bin/bash
 
+printf  "MPI test (ring test)\n"
+printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
 # pull container
 #podman pull krccl/openmpi_base:403
-podman build . -t testing-ring
+printf "Attempting to build mpi base container.. "
+if podman build . -t testing-ring > /dev/null 2>&1 ; then
+	printf "done\n"
+else
+	printf "failed\n"
+	exit 1
+fi
 
-# compile from host 
+# compile 
+printf "Attempting to compile ring.c.. "
+if /usr/lib64/openmpi/bin/mpicc -o ring-out ./ring/ring.c > /dev/null 2>&1 ; then
+	printf "done\n"
+else
+	printf "failed\n"
+	exit 1
+fi
 
-# compile from within container
 
 # mpirun
 
 #export PMIX_MCA_gds=hash
 # mpirun --mca btl openib,tcp,self --mca orte_tmpdir_base /tmp/podman-mpirun -n 3 podman run --userns=keep-id -v /home/opc/podman-tests/ring:/home/opc/ring --env-host --net=host --pid=host --ipc=host krccl/openmpi_base:403 /home/opc/ring/ringo
-podman run --userns=keep-id -v /home/opc/podman-tests/ring:/home/opc/ring --env-host --net=host --pid=host --ipc=host testing-ring /usr/lib64/openmpi/bin/mpirun  --mca btl openib,tcp,self -np 3 /home/opc/ring/ringo
-export PMIX_MCA_gds=
+printf "Attempting to run ring..\n"
+if podman run --userns=keep-id -v /home/opc/podman-tests/ring:/home/opc/ring --env-host --net=host --pid=host --ipc=host testing-ring /usr/lib64/openmpi/bin/mpirun  --mca btl openib,tcp,self -np 3 /home/opc/ring/ring-out ; then
+	printf "done\n"
+	printf "TEST PASSED\n"
+	exit 0
+else
+	printf "failed\n"
+	printf "TEST FAILED\n"
+	exit 1
+fi
+#export PMIX_MCA_gds=
